### PR TITLE
Adding Unifi Identity Enterprise for SAML walkthrough

### PR DESCRIPTION
**Pull request by KarmaPoliceT2**
This PR adds a docs section to help users configure UniFi Identity Enterprise to be the SAML provider for Omni (doc is written for on-prem environment, but should be applicable anywhere).

### CODE REVIEW

**Comment by TimJones** [comment]
Hi! Thanks for the contribution, if you could squash the commits down to a single comment and rebase off of main, I can then sign and merge.

Many thanks!

**Comment by KarmaPoliceT2** [comment]
Think this is correct now... let me know if not.

**Comment by TimJones** [comment]
Yup, perfect, thanks again!

**Review by TimJones — APPROVED** [review]

**Pull request closed without merging**
